### ISSUE TITLE
Tests out of sequence.  Found (2) but expected (1)

### ISSUE THREAD

**Issue by eserte** [shlomif/App-Timestamper#1]
On one of my smokers the test suite fails. Running the t/output-flag.t manually show the following:
```
$ perl5.30.0 -Mblib t/output-flag.t
1..2
1634537935.83105397    one
1634537935.83143711    two
1634537935.83147001    three
1634537935.93106198
0.10090995 elapsedok 1 - first line
ok 2 - 2nd line
```
So "ok 1" is never seen by the test harness. 

On this system IO::Async::Stream 0.72 is installed, but it seems that there are also pass reports with this version installed.

**Comment by eserte** [comment]
(This is a report for App-Timestamper-WithElapsed-0.6.0)

**Comment by shlomif** [comment]
@eserte : hi! Thanks - please try with v0.6.1.

**Comment by eserte** [comment]
The current version on CPAN looks fine.
